version: '3.8'

services:
  db_bot:
    image: postgres:15
    container_name: db_bot
    restart: always
    ports:
      - 1271:5432
    volumes:
      - db_data_bot:/var/lib/postgresql/data
    env_file:
      - .env
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always

  bot:
    build:
      context: .
    env_file:
      - .env
    container_name: bot
    restart: always
    command: bash -c "make migrate && make run_bot"
    ports:
      - 8080:8080
    depends_on:
      - nginx
      - db_bot




volumes:
  db_data_bot: